modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Rexbas/Teletubbies-Mod/issues"
logoFile="logo.png"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://forge.curseupdate.com/236040/teletubbies"
displayURL="https://www.curseforge.com/minecraft/mc-mods/teletubbies-mod"
authors="${mod_authors}"
credits="${mod_credits}"
description='''${mod_description}'''
[[dependencies.bouncingballs]]
    modId="bouncingballs_api"
    mandatory=true
    versionRange="${boucing_balls_api_version_range}"
    ordering="AFTER"
    side="BOTH"