modLoader="javafml"
loaderVersion="[40,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Rexbas/Teletubbies-Mod/issues"
logoFile="logo.png"
[[mods]]
modId="teletubbies"
version="${file.jarVersion}"
displayName="Teletubbies"
updateJSONURL="https://forge.curseupdate.com/236040/teletubbies"
displayURL="https://www.curseforge.com/minecraft/mc-mods/teletubbies-mod"
credits="McHorse (Dome parts)"
authors="Rexbas"
description='''
Teletubbies for Minecraft!
'''
[[dependencies.bouncingballs]]
    modId="bouncingballs_api"
    mandatory=true
    versionRange="[3.0.1,)"
    ordering="AFTER"
    side="BOTH"